### ISSUE TITLE
Adicionar como contribuir diretamente pelo github na página de boas vindas

### ISSUE THREAD

**Issue by victoragcosta** [StructEC/gitbook#6]
# Precisa conter:
* Como chegar ao repositório
  * Indicar que deve clonar e fazer tudo por lá
  * Indicar o desligamento da Struct caso dê commit na master
* Como criar uma branch para criar o conteúdo
* Como fazer fork para criar o conteúdo
* Como fazer pull request
* Padrões utilizados no gitbook
  * Criar links no menu lateral da esquerda
  * Criar páginas novas
  * Criar páginas com subpáginas
  * Criar grupos com subpáginas
  * Referência a um tutorial de markdown
  * Indicar sobre como organizar os headers (H1 somente para o título da página e nunca pule nível)

**Comment by AndreLaranjeira** [comment]
Vou modificar um pouco essa issue para simplificar a página e não gerar uma página sobrecarregada.

1) Essa issue **não vai ser uma página nova**, mas sim uma seção na página principal do Gitbook.

2) Na subseção de Git e GitHub, não explique conceitos básicos de git como clone, fork, pull, etc... porque isso vai entulhar a página. Coloque uma frase no início explicando que conhecimentos básicos de Git são necessários para contribuir e coloque um link para uma aula de trainee ou o livro "Git pro" \(que é gratuito, se não me engano\) para caso a pessoa não saiba como mexer com o Git. Nessa parte do Git e Github em si, explique apenas conceitos importantes como:

- Não faça mudanaçs diretamente na master (pode manter ~a ameaça de~ a piada do desligamento);
- Crie uma branch para realizar modificações (sem caracteres especiais como '&', isso quebra o Gitbook);
- Verifique a branch no ambiente de deploy antes de abrir a PR;
- Abra uma PR e peça review para alguém;

3) Na subseção de padrões utilizados no Gitbook, colocar os seguintes conceitos:

- Como funciona o Gitbook, o que é markdown (mas não como escrever markdown, isso pode ser um link), o arquivo SUMMARY, e as estruturas de pastas dos arquivos markdown;
- Explicar que nem sempre o markdown que funciona no GitHub funcionará no Gitbook e por isso ver o ambiente de deploy é **essencial**;
- Explicar padrões de nomes de arquivos e de pastas de imagens;
- Explicar que headers devem sempre ser decrescentes começando de H1 (somente para título de página) e nunca pular nível.

4) Criar uma seção de dicas úteis com as seguintes grafias recorrentes (na vibe de um cheatsheet e não de tutorial de markdown):

- Links normais (em que eu defina um texto e uma URL);
- Código fonte;
- Tabelas;
- Links para outras páginas do próprio markdown (esse é um dos mais importantes);
- Imagens;

**Comment by AndreLaranjeira** [comment]
Closed by #21.
